/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as MySettingsRouteImport } from './routes/my-settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as CloudAgentsRouteImport } from './routes/cloud-agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const MySettingsRoute = MySettingsRouteImport.update({
  id: '/my-settings',
  path: '/my-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudAgentsRoute = CloudAgentsRouteImport.update({
  id: '/cloud-agents',
  path: '/cloud-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cloud-agents': typeof CloudAgentsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/my-settings': typeof MySettingsRoute
  '/review': typeof ReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cloud-agents': typeof CloudAgentsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/my-settings': typeof MySettingsRoute
  '/review': typeof ReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cloud-agents': typeof CloudAgentsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/my-settings': typeof MySettingsRoute
  '/review': typeof ReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cloud-agents'
    | '/integrations'
    | '/login'
    | '/my-settings'
    | '/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cloud-agents'
    | '/integrations'
    | '/login'
    | '/my-settings'
    | '/review'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cloud-agents'
    | '/integrations'
    | '/login'
    | '/my-settings'
    | '/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CloudAgentsRoute: typeof CloudAgentsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  MySettingsRoute: typeof MySettingsRoute
  ReviewRoute: typeof ReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-settings': {
      id: '/my-settings'
      path: '/my-settings'
      fullPath: '/my-settings'
      preLoaderRoute: typeof MySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-agents': {
      id: '/cloud-agents'
      path: '/cloud-agents'
      fullPath: '/cloud-agents'
      preLoaderRoute: typeof CloudAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CloudAgentsRoute: CloudAgentsRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  MySettingsRoute: MySettingsRoute,
  ReviewRoute: ReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
