"""ORM mappings for the pull request tables.

Migration ``0011_pull_requests`` is the source of truth for the schema; these
mappings must match it column for column. Ids are UUIDv7 generated by the
application, never by the database.
"""

from datetime import datetime
from uuid import UUID

from sqlalchemy import BigInteger, DateTime, ForeignKey, Text, UniqueConstraint, desc, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

_NOW = text("clock_timestamp()")


class Row(DeclarativeBase):
    type_annotation_map = {datetime: DateTime(timezone=True), str: Text}


class RepositoryRow(Row):
    __tablename__ = "repository"

    id: Mapped[UUID] = mapped_column(primary_key=True)
    key: Mapped[str] = mapped_column(unique=True)
    full_name: Mapped[str]
    private: Mapped[bool | None]
    default_branch: Mapped[str] = mapped_column(server_default="")
    first_seen_at: Mapped[datetime] = mapped_column(server_default=_NOW)
    last_activity_at: Mapped[datetime] = mapped_column(server_default=_NOW)


class PullRequestRow(Row):
    __tablename__ = "pull_request"
    __table_args__ = (UniqueConstraint("repository_id", "number"),)

    id: Mapped[UUID] = mapped_column(primary_key=True)
    repository_id: Mapped[UUID] = mapped_column(ForeignKey("repository.id"))
    number: Mapped[int]
    owner: Mapped[str]
    repo: Mapped[str]
    state: Mapped[str] = mapped_column(server_default="open")
    title: Mapped[str] = mapped_column(server_default="")
    head_ref: Mapped[str] = mapped_column(server_default="")
    base_ref: Mapped[str] = mapped_column(server_default="")
    author: Mapped[str] = mapped_column(server_default="")
    resolves_thread: Mapped[bool] = mapped_column(server_default=text("false"))
    created_at: Mapped[datetime] = mapped_column(server_default=_NOW)
    updated_at: Mapped[datetime] = mapped_column(server_default=_NOW)

    repository: Mapped[RepositoryRow] = relationship()
    threads: Mapped[list[PullRequestThreadRow]] = relationship(
        cascade="all, delete-orphan",
        order_by=lambda: (
            desc(PullRequestThreadRow.role == "primary"),
            PullRequestThreadRow.linked_at,
            PullRequestThreadRow.thread_id,
        ),
    )
    reviews: Mapped[list[PullRequestReviewRow]] = relationship(
        cascade="all, delete-orphan",
        order_by=lambda: (PullRequestReviewRow.published_at, PullRequestReviewRow.id),
    )


class PullRequestThreadRow(Row):
    __tablename__ = "pull_request_thread"

    pull_request_id: Mapped[UUID] = mapped_column(
        ForeignKey("pull_request.id", ondelete="CASCADE"), primary_key=True
    )
    thread_id: Mapped[str] = mapped_column(primary_key=True)
    role: Mapped[str]
    source: Mapped[str] = mapped_column(server_default="")
    linked_at: Mapped[datetime] = mapped_column(server_default=_NOW)


class PullRequestReviewRow(Row):
    __tablename__ = "pull_request_review"

    id: Mapped[UUID] = mapped_column(primary_key=True)
    pull_request_id: Mapped[UUID] = mapped_column(ForeignKey("pull_request.id", ondelete="CASCADE"))
    reviewer_thread_id: Mapped[str] = mapped_column(server_default="")
    github_review_id: Mapped[int | None] = mapped_column(BigInteger)
    url: Mapped[str] = mapped_column(server_default="")
    head_sha: Mapped[str] = mapped_column(server_default="")
    finding_count: Mapped[int | None]
    published_at: Mapped[datetime] = mapped_column(server_default=_NOW)
