/*
 * Extracts the stylesheet half of the system: the token values, the utility
 * ladder those tokens generate, and the bridge that re-points a shadcn
 * consumer's own variable names at our tokens.
 *
 * The bridge is the whole reason a consumer can adopt this in two lines. A
 * Tailwind v4 shadcn app indirects every utility through a bare custom
 * property, so redefining that one layer re-skins every component the consumer
 * already has, including the ones we never shipped them.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = dirname(here);
const web = dirname(dirname(pkg));
const out = join(pkg, "src", "styles");
const VERIFY = process.argv.includes("--verify");

function block(css, selector) {
  const start = css.indexOf(selector);
  if (start === -1) throw new Error(`selector not found: ${selector}`);
  const open = css.indexOf("{", start);
  let depth = 0;
  for (let i = open; i < css.length; i += 1) {
    if (css[i] === "{") depth += 1;
    if (css[i] === "}") {
      depth -= 1;
      if (depth === 0) return css.slice(start, i + 1);
    }
  }
  throw new Error(`unterminated block: ${selector}`);
}

const tokens = readFileSync(join(web, "src/styles/tokens.css"), "utf8");
const elevation = readFileSync(join(web, "src/styles/elevation.css"), "utf8");
const globals = readFileSync(join(web, "src/app/globals.css"), "utf8");

/*
 * Consumers on shadcn's class-based dark variant and consumers on our attribute
 * both have to work, so the variant matches either. The app's own sheet keys on
 * the attribute alone; widening it here costs nothing and removes the single
 * most likely silent failure in a port.
 */
const DARK_VARIANT =
  '@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *, .dark, .dark *));';

const theme = block(globals, "@theme inline");
const utilities = globals.slice(globals.indexOf("@utility duration-fast"));

const BRIDGE = `/*
 * shadcn bridge, part of the GTM Platform internal design system created by
 * Amal Irgashev.
 *
 * Maps a shadcn/ui consumer's variable names onto our tokens, in both themes.
 * Import this only if the consuming app already has shadcn components: it
 * re-skins them in place, with no component edits. An app with no shadcn
 * primitives should skip it.
 *
 * Generated by scripts/extract-styles.mjs. Edit the map there, never here.
 */

:root,
[data-theme="light"] {
  --background: var(--gtm-canvas);
  --foreground: var(--gtm-ink);
  --card: var(--gtm-panel);
  --card-foreground: var(--gtm-ink);
  --popover: var(--gtm-panel);
  --popover-foreground: var(--gtm-ink);
  --primary: var(--gtm-primary);
  --primary-foreground: var(--gtm-primary-ink);
  --secondary: var(--gtm-muted);
  --secondary-foreground: var(--gtm-ink);
  --muted: var(--gtm-muted);
  --muted-foreground: var(--gtm-ink-subtle);
  --accent: var(--gtm-hover);
  --accent-foreground: var(--gtm-ink);
  --destructive: var(--gtm-risk);
  --destructive-foreground: var(--gtm-panel);
  --border: var(--gtm-line);
  --input: var(--gtm-line-strong);
  --ring: var(--gtm-primary);

  /*
   * Named state roles.
   *
   * Our family names the INK (\`--gtm-risk\`) and its TINT (\`--gtm-risk-bg\`)
   * separately; shadcn names a solid fill and the ink that sits on it. A
   * solid role therefore takes our ink as its fill, with panel on top, and the
   * tint is exposed beside it for the subtle treatment a badge wants. Pick by
   * weight: \`bg-destructive text-destructive-foreground\` for a button,
   * \`bg-destructive-tint text-destructive-ink\` for a badge. Mixing them is
   * what breaks the equal-contrast guarantee.
   */
  --success: var(--gtm-positive);
  --success-foreground: var(--gtm-panel);
  --success-tint: var(--gtm-positive-bg);
  --success-ink: var(--gtm-positive);
  --warning: var(--gtm-attention);
  --warning-foreground: var(--gtm-panel);
  --warning-tint: var(--gtm-attention-bg);
  --warning-ink: var(--gtm-attention);
  --info: var(--gtm-info);
  --info-foreground: var(--gtm-panel);
  --info-tint: var(--gtm-info-bg);
  --info-ink: var(--gtm-info);
  --destructive-tint: var(--gtm-risk-bg);
  --destructive-ink: var(--gtm-risk);

  /* Chrome surfaces, back to front. */
  --surface-raised: var(--gtm-shell);
  --app-chrome-background: var(--gtm-desk);
  --sidebar: var(--gtm-sidebar);
  --sidebar-foreground: var(--gtm-ink);
  --sidebar-muted-foreground: var(--gtm-ink-subtle);
  --sidebar-border: var(--gtm-line);
  --sidebar-ring: var(--gtm-primary);
  --sidebar-primary: var(--gtm-primary);
  --sidebar-primary-foreground: var(--gtm-primary-ink);
  --sidebar-accent: var(--gtm-hover);
  --sidebar-accent-foreground: var(--gtm-ink);
  --sidebar-control-surface: var(--gtm-panel);
  --sidebar-row-hover: var(--gtm-hover);
  --sidebar-row-active: var(--gtm-selected);
  --sidebar-row-selected: var(--gtm-selected);

  --radius: var(--radius-panel, 0.5rem);
}

/*
 * The dark half needs no second map: every name above resolves through a
 * \`--gtm-*\` token, and tokens.css already flips those. This block exists only
 * for a consumer driving \`.dark\` as a class, where the attribute selector in
 * tokens.css never matches.
 */
.dark {
  color-scheme: dark;
}
`;

const files = {
  "tokens.css": tokens,
  "elevation.css": elevation,
  "theme.css": [
    "/*",
    " * The GTM Platform internal design system, created by Amal Irgashev.",
    " *",
    " * Generated by scripts/extract-styles.mjs. Source: web/src/app/globals.css.",
    " */",
    "",
    '@import "./tokens.css";',
    '@import "./elevation.css";',
    "",
    DARK_VARIANT,
    "",
    theme,
    "",
    utilities,
  ].join("\n"),
  "bridge.css": BRIDGE,
};

let stale = false;
for (const [name, body] of Object.entries(files)) {
  const target = join(out, name);
  if (VERIFY) {
    const have = existsSync(target) ? readFileSync(target, "utf8") : null;
    if (have !== body) {
      console.error(`DRIFT styles/${name}`);
      stale = true;
    }
  } else {
    writeFileSync(target, body);
    console.log(`wrote styles/${name} (${body.split("\n").length} lines)`);
  }
}
if (stale) process.exit(1);
