/*
 * Convenience barrel. Generated by scripts/build-index.mjs.
 *
 * Prefer the subpath (`@langchain/gtm-platform-design-system/patterns/page-frame`) in application
 * code: it is what keeps a bundle honest, and it is what agent/index.json
 * hands an agent. This exists for exploration and for a consumer whose
 * bundler already tree-shakes ESM re-exports.
 *
 * Names defined in more than one module, resolved first-wins:
 *   ExpandedRow: patterns/filterable-table wins over data-grid/data-grid-expanded-rows
 *   Box: ui/box wins over ui/glyphs
 *   Calendar: ui/calendar wins over ui/glyphs
 *   Orb: ui/orb wins over ui/glyphs
 */

export * from "./host";
export { DataGrid, DataGridContainer, DataGridProvider, getColumnHeaderLabel, useDataGrid } from "./data-grid/data-grid";
export { DataGridColumnFilter } from "./data-grid/data-grid-column-filter";
export { DataGridColumnHeader } from "./data-grid/data-grid-column-header";
export { DataGridColumnVisibility } from "./data-grid/data-grid-column-visibility";
export { ArrowDownGlyph, ArrowLeftGlyph, ArrowLeftToLineGlyph, ArrowRightGlyph, ArrowRightToLineGlyph, ArrowUpGlyph, CheckGlyph, ChevronDownGlyph, ChevronLeftGlyph, ChevronRightGlyph, ChevronsUpDownGlyph, CirclePlusGlyph, ColumnsGlyph, PinFilledGlyph, PinGlyph, PinOffGlyph } from "./data-grid/data-grid-glyphs";
export { DataGridLoadMoreSentinel } from "./data-grid/data-grid-load-more";
export { DataGridPagination } from "./data-grid/data-grid-pagination";
export { DataGridTable, DataGridTableBase, DataGridTableBody, DataGridTableBodyRow, DataGridTableBodyRowCell, DataGridTableBodyRowExpandded, DataGridTableBodyRowSkeleton, DataGridTableBodyRowSkeletonCell, DataGridTableEmpty, DataGridTableFillBodyCell, DataGridTableFillHeadCell, DataGridTableFoot, DataGridTableFootRow, DataGridTableFootRowCell, DataGridTableHead, DataGridTableHeadRow, DataGridTableHeadRowCell, DataGridTableHeadRowCellResize, DataGridTableHeadRows, DataGridTableHeader, DataGridTableLoader, DataGridTableRenderedRow, DataGridTableRowExpand, DataGridTableRowPin, DataGridTableRowSelect, DataGridTableRowSelectAll, DataGridTableRowSpacer, DataGridTableServerGrouped, DataGridTableViewport, getDataGridScrollAreaViewport, getDataGridTableMergedHeaderGroups, getDataGridTableResolvedRows, getDataGridTableRowSections, getDataGridTreeIndentStyle, getPinningStyles, hasDataGridTableRightPinnedColumns } from "./data-grid/data-grid-table";
export { DataGridTableVirtual } from "./data-grid/data-grid-table-virtual";
export { AgentInterpretation, AgentThread, AgentThreadDivider, AgentTurn, TurnCopyButton, UserTurn, UserTurnCopy } from "./patterns/agent-thread";
export { AgentThreadMenu, AgentThreadRail } from "./patterns/agent-thread-rail";
export { AppRailPreview, PREVIEW_ITEM_LIMIT } from "./patterns/app-rail-preview";
export { AppShell } from "./patterns/app-shell";
export { CapacityMeter, CapacityMetric, CapacityMetricGrid, getCapacityTone } from "./patterns/capacity-metric";
export { ChangeFeed, DEFAULT_COLLAPSED_COUNT, ListContinuation, ListViewport, clipList } from "./patterns/change-feed";
export { ChoiceCards } from "./patterns/choice-cards";
export { ComingUpCalendar, ComingUpModeToggle } from "./patterns/coming-up-calendar";
export { ConfirmableAction } from "./patterns/confirmable-action";
export { CONVERSATION_STATUS_LABEL, ConversationRow, ConversationStatusBadge } from "./patterns/conversation-row";
export { DataScopeSelect } from "./patterns/data-scope-select";
export { DecisionList, DecisionRow } from "./patterns/decision-row";
export { ChangeSet, ChangeSetSection, DiffRow } from "./patterns/diff-row";
export { EmptyState } from "./patterns/empty-state";
export { ExpandedRow, FilterableTable, FilterableTableGroupControl, FilterableTableGroupRow, FilterableTableGroupTag, filterableTableSplitFrame } from "./patterns/filterable-table";
export { FormField, FormSection, FormStack, SECTION_STACK_GAP } from "./patterns/form-field";
export { InputQuestionField, InputRequestComposer, InputRequestPausedRow, InputRequestReceipt, InputRequestSectionFields, InputRequestSubmission, formatInputRequestAnswer, hasInputRequestErrors, resolveInputRequestPresentation, validateInputRequestSection } from "./patterns/input-request";
export { MetricCard, MetricCardGrid } from "./patterns/metric-card";
export { OnboardingDialog } from "./patterns/onboarding-dialog";
export { OverflowTabs, splitOverflowTabs } from "./patterns/overflow-tabs";
export { PageBand } from "./patterns/page-band";
export { PAGE_STACK_CLASS, PageFrame, PageSection } from "./patterns/page-frame";
export { PageMasthead } from "./patterns/page-masthead";
export { PostureControl } from "./patterns/posture-control";
export { ProviderAction } from "./patterns/provider-action";
export { ProviderMark } from "./patterns/provider-mark";
export { QueueList, QueueRow } from "./patterns/queue-row";
export { Receipt } from "./patterns/receipt";
export { RecordFact, RecordHeader, RecordHop, RecordInlineEdit } from "./patterns/record-header";
export { ReviewBand } from "./patterns/review-band";
export { SchemaCellPreview, SchemaCount, SchemaDate, SchemaEnum, SchemaHeader, SchemaLink, SchemaMoney, SchemaSet, SchemaText, splitSchemaSet } from "./patterns/schema-cell";
export { SettingRow, SettingSection } from "./patterns/setting-section";
export { SidebarNav, SidebarNavChild, SidebarNavCluster, SidebarNavGroup, SidebarNavItem } from "./patterns/sidebar-nav";
export { SidebarTreeGroup, SidebarTreeRow } from "./patterns/sidebar-tree";
export { SiteMark } from "./patterns/site-mark";
export { LIST_COLLAPSED_WIDTH, LIST_SIDEBAR_CHROME_CLASS, LIST_WIDTH_DEFAULT, LIST_WIDTH_MAX, LIST_WIDTH_MIN, ListSidebarChrome, ListSidebarTitle, REFERENCE_WIDTH_MAX, REFERENCE_WIDTH_MIN, SplitView } from "./patterns/split-view";
export { StatReadout, StatReadoutGrid } from "./patterns/stat-readout";
export { StateNotice } from "./patterns/state-notice";
export { RANGE_SEPARATOR, TableFilterPills, TableFilters, VALUES_SEPARATOR, appliedScopeTabs, countFilterValues, formatFilterValue, isFilterValueSet, joinRange, joinValues, splitRange, splitValues, toggleValue } from "./patterns/table-filters";
export { PublishGate, VersionedEditor } from "./patterns/versioned-editor";
export { WizardBranchBack, WizardBranchPane, WizardDialog } from "./patterns/wizard-dialog";
export { PromptInput } from "./ui/ai-chat-input";
export { Alert, AlertDescription, AlertTitle } from "./ui/alert";
export { Avatar, deriveInitials, deriveTone } from "./ui/avatar";
export { Badge, badgeVariants } from "./ui/badge";
export { Box, Inline, Stack } from "./ui/box";
export { Button, buttonVariants } from "./ui/button";
export { Calendar } from "./ui/calendar";
export { Checkbox } from "./ui/checkbox";
export { CheckboxGroup, CheckboxGroupItem, CheckboxGroupSelectAll } from "./ui/checkbox-group";
export { cn } from "./ui/cn";
export { Collapsible, CollapsibleChevron, CollapsibleContent, CollapsibleTrigger } from "./ui/collapsible";
export { Combobox, ComboboxContent, ComboboxEmpty, ComboboxGroup, ComboboxInput, ComboboxItem, ComboboxList, ComboboxSeparator, ComboboxTrigger, FIELD_TRIGGER_CLASS } from "./ui/combobox";
export { Command, CommandEmpty, CommandFooter, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator, CommandShortcut } from "./ui/command";
export { ContextMenu, ContextMenuCheckboxItem, ContextMenuContent, ContextMenuItem, ContextMenuTrigger } from "./ui/context-menu";
export { ConversationNavigator } from "./ui/conversation-navigator";
export { DATE_DISPLAY_FORMAT, DATE_RANGE_SEPARATOR, DatePicker, formatRangeValue, formatSingleValue } from "./ui/date-picker";
export { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogOverlay, DialogPortal, DialogTitle, DialogTrigger } from "./ui/dialog";
export { DropdownMenu, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuPortal, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from "./ui/dropdown-menu";
export { Elevated, MAX_ELEVATION_LEVEL, SurfaceProvider, elevationClasses, elevationLevel, useSurface } from "./ui/elevated";
export { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "./ui/empty";
export { FadeText } from "./ui/fade-text";
export { FIELD_FOCUS_CLASS, FIELD_FOCUS_PAINTED_CLASS, FIELD_INVALID_CLASS } from "./ui/field-focus";
export { Frame, FrameDescription, FrameFooter, FrameHeader, FramePanel, FrameTitle, frameVariants } from "./ui/frame";
export { AlertTriangle, ArchiveBox, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ArrowUpRight, Bell, Bot, Building2, CalendarDays, Check, CheckCircle, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ChevronsLeft, ChevronsRight, ChevronsUpDown, Circle, Clock, Cloud, Columns, Copy, CornerDownLeft, Database, DollarSign, Ellipsis, Expand, ExternalLink, File, FileEdit, FilePlus, FileSpreadsheet, FileText, Filter, Folder, FolderOpen, Globe, Home, Image, Inbox, Info, Layers, LayoutGrid, LineChart, List, ListChecks, Loader2, Lock, Mail, Megaphone, MessageSquare, Minus, Moon, Palette, PanelLeft, PanelRight, Paperclip, Pause, Pencil, Pin, PinFilled, PinOff, Play, Plus, PlusCircle, PushPin, QuestionMarkCircle, RefreshCw, RotateCcw, Search, Send, Server, Settings2, Share2, Square, Star, Sun, Table2, Target, Terminal, Trash2, TrendingUp, Upload, User, Users, Wrench, X, XCircle, Zap } from "./ui/glyphs";
export { GroupRowContent } from "./ui/group-row";
export { HOVER_CARD_CLOSE_DELAY, HOVER_CARD_DELAY, HoverCard, HoverCardContent, HoverCardTrigger } from "./ui/hover-card";
export { Icon } from "./ui/icon";
export { ICON_WELL_CLASS, IconWell } from "./ui/icon-well";
export { FIELD_VALUE_CLASS, Input } from "./ui/input";
export { InputCopy } from "./ui/input-copy";
export { Kbd } from "./ui/kbd";
export { HELP_CLASS, LABEL_CLASS, Label } from "./ui/label";
export { htmlToMarkdown, markdownToHtml } from "./ui/markdown-codec";
export { MarkdownEditor, getMarkdownEditor, setMarkdownEditorValue } from "./ui/markdown-editor";
export { MentionChip, MentionChipFace, MentionChipPeek } from "./ui/mention-chip";
export { ORB_CAPTION, ORB_RUNG_PX, ORB_STATE_FOR_ACTIVITY, Orb, OrbStatus } from "./ui/orb";
export { OrbFull, OrbMicro, OrbMini } from "./ui/orb-glyph";
export { Popover, PopoverArrow, PopoverClose, PopoverContent, PopoverTrigger } from "./ui/popover";
export { POPUP_SURFACE, POPUP_SURFACE_DENSE, POPUP_SURFACE_FLUSH, POPUP_SURFACE_MOTION, POPUP_SURFACE_PADDED, POPUP_SURFACE_SHELL } from "./ui/popup-surface";
export { Progress } from "./ui/progress";
export { GoogleMark, MailProviderLogo, ProviderLogo, isMailProviderLogoId, isProviderLogoId } from "./ui/provider-logos";
export { PushPinFull, PushPinMicro, PushPinMini } from "./ui/pushpin-glyph";
export { RadioGroup, RadioGroupItem } from "./ui/radio-group";
export { SCROLL_HOST_CLASS, ScrollArea, ScrollAreaBody, ScrollBar } from "./ui/scroll-area";
export { ScrollFadeContainer } from "./ui/scroll-fade-container";
export { SearchInput } from "./ui/search-input";
export { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectSeparator, SelectTrigger, SelectValue } from "./ui/select";
export { Separator } from "./ui/separator";
export { Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger } from "./ui/sheet";
export { Shortcut, parseShortcutString, shortcutAriaKeyshortcuts, shortcutKeyLabel } from "./ui/shortcut";
export { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupAction, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInput, SidebarInset, SidebarMenu, SidebarMenuAction, SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarMenuSkeleton, SidebarMenuSub, SidebarMenuSubButton, SidebarMenuSubItem, SidebarProvider, SidebarRail, SidebarSeparator, SidebarTrigger, useSidebar } from "./ui/sidebar";
export { Skeleton } from "./ui/skeleton";
export { Slider, sliderControlVariants } from "./ui/slider";
export { Toaster } from "./ui/sonner";
export { Spinner, StatusLabel } from "./ui/spinner";
export { SpinnerFull, SpinnerMicro, SpinnerMini } from "./ui/spinner-glyph";
export { Switch } from "./ui/switch";
export { Table, TableBody, TableCaption, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "./ui/table";
export { Tabs, TabsContent, TabsList, TabsTrigger, tabsListVariants } from "./ui/tabs";
export { Textarea } from "./ui/textarea";
export { Timeline, TimelineContent, TimelineDate, TimelineHeader, TimelineIndicator, TimelineItem, TimelineSeparator, TimelineTitle } from "./ui/timeline";
export { ToggleGroup, ToggleGroupItem } from "./ui/toggle-group";
export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "./ui/tooltip";
