from typing import Any, cast

from langchain_core.messages import AIMessage, HumanMessage

from agent.input_messages import human_input, system_input
from agent.middleware.firehose import FirehoseMiddleware, _authored_turns
from agent.utils import slack_firehose


def _slack_turn(text: str, *, message_id: str | None = None) -> HumanMessage:
    message = human_input(
        text,
        {"sender_id": "person:U_HUMAN", "surface": "slack", "kind": "human"},
    )
    return HumanMessage(content=cast(str, message["content"]), id=message_id)


def _open_swe_block(text: str) -> HumanMessage:
    message = system_input(
        text,
        {"sender_id": "system:open-swe", "surface": "slack", "kind": "system"},
    )
    return HumanMessage(content=cast(str, message["content"]))


def test_only_authored_turns_are_mirrored():
    framing = _open_swe_block("Slack thread context follows.")
    turn = _slack_turn("please add a greet() helper")
    metadata = _open_swe_block("Sender metadata generated by Open SWE.")
    plain = HumanMessage(content="a desktop message carries no envelope")

    turns = _authored_turns([framing, turn, metadata, plain, AIMessage(content="working")])

    assert [message.content for message in turns] == [turn.content, plain.content]


async def test_only_the_newest_turn_is_mirrored_on_run_start(monkeypatch):
    recorded: list[dict[str, Any]] = []
    monkeypatch.setattr(
        slack_firehose,
        "_enqueue",
        lambda thread_id, work: None,
    )
    monkeypatch.setattr(
        "agent.middleware.firehose.record_inbound",
        lambda thread_id, **kwargs: recorded.append({"thread_id": thread_id, **kwargs}),
    )
    middleware = FirehoseMiddleware(thread_id="t1", source="slack", requester="ramon")
    old = _slack_turn("the first request", message_id="h1")
    new = _slack_turn("the follow-up", message_id="h2")

    await middleware.abefore_agent({"messages": [old, new]}, None)  # type: ignore[arg-type]

    assert [entry["text"] for entry in recorded] == ["the follow-up"]

    # A mid-run message queued into state is picked up on the next model call.
    queued = _slack_turn("one more thing", message_id="h3")
    await middleware.aafter_model(
        {"messages": [old, new, AIMessage(content="ok"), queued]},  # type: ignore[arg-type]
        None,  # type: ignore[arg-type]
    )
    assert [entry["text"] for entry in recorded] == ["the follow-up", "one more thing"]


async def test_synthetic_tool_calls_stay_out_of_the_firehose(monkeypatch):
    recorded: list[dict[str, Any]] = []
    monkeypatch.setattr(
        "agent.middleware.firehose.record_turn",
        lambda thread_id, **kwargs: recorded.append({"thread_id": thread_id, **kwargs}),
    )
    middleware = FirehoseMiddleware(thread_id="t2", source="dashboard")
    message = AIMessage(
        content="checking",
        tool_calls=[
            {"name": "no_op", "args": {}, "id": "1"},
            {"name": "execute", "args": {"command": "ls"}, "id": "2"},
        ],
    )

    await middleware.aafter_model({"messages": [message]}, None)  # type: ignore[arg-type]

    assert [call["name"] for call in recorded[0]["tool_calls"]] == ["execute"]
