"""Docker sandbox provider for local containerized development.

Runs each agent session inside a local Docker container via the ``docker-py``
library.  Provides the same ``SandboxBackendProtocol`` interface as the cloud
providers (LangSmith, Daytona, …) but requires only a running Docker daemon —
no API keys, no network egress for sandbox I/O.

Usage::

    SANDBOX_TYPE=docker python -m agent.webapp
    # custom image:
    DOCKER_SANDBOX_IMAGE=python:3.12-slim SANDBOX_TYPE=docker ...

Environment variables:

- ``DOCKER_SANDBOX_IMAGE`` — base container image (default: ``ubuntu:22.04``).
- ``DOCKER_SANDBOX_WORKSPACE`` — working directory inside the container
  (default: ``/workspace``).
"""

from __future__ import annotations

import io
import os
import shlex
import tarfile

from deepagents.backends.protocol import (
    ExecuteResponse,
    FileDownloadResponse,
    FileUploadResponse,
)
from deepagents.backends.sandbox import BaseSandbox

DOCKER_DEFAULT_IMAGE = "ubuntu:22.04"
DOCKER_IMAGE_ENV = "DOCKER_SANDBOX_IMAGE"
DOCKER_WORKSPACE_ENV = "DOCKER_SANDBOX_WORKSPACE"
DOCKER_DEFAULT_WORKSPACE = "/workspace"


class DockerSandbox(BaseSandbox):
    """Local Docker container sandbox.

    Implements :class:`~deepagents.backends.sandbox.BaseSandbox` by mapping
    ``execute()`` to ``docker exec`` and file I/O to the Docker tar-archive
    API (``put_archive`` / ``get_archive``).

    All other protocol methods (``ls``, ``read``, ``write``, ``edit``,
    ``grep``, ``glob``) are derived automatically from ``execute()`` and
    ``upload_files()`` by ``BaseSandbox``.

    The container is kept alive with ``tail -f /dev/null`` as its long-running
    command.  All agent commands are run via a new ``docker exec`` call so
    each invocation is independent.
    """

    def __init__(self, container, workspace: str = DOCKER_DEFAULT_WORKSPACE) -> None:
        self._container = container
        self._workspace = workspace

    @property
    def id(self) -> str:
        """Unique identifier — the Docker container ID."""
        return self._container.id

    def execute(
        self,
        command: str,
        *,
        timeout: int | None = None,
    ) -> ExecuteResponse:
        """Run a shell command inside the container via ``docker exec``.

        Args:
            command: Full shell command string to execute.
            timeout: Optional time limit in seconds.  Wraps the command in
                ``timeout N bash -c <command>`` so that the inner bash process
                (which handles heredocs, pipes, and redirects generated by
                ``BaseSandbox``) is correctly terminated after N seconds.

        Returns:
            :class:`~deepagents.backends.protocol.ExecuteResponse` with
            combined stdout/stderr, exit code, and ``truncated=False``.
        """
        if timeout is not None:
            # Use `timeout N bash -c command` so the inner bash process handles
            # heredocs/pipes/redirects correctly.  Do NOT use the alternative
            # `bash -c "timeout N {command}"` form: that binds any heredoc in
            # `command` to the stdin of `timeout` rather than to the embedded
            # command, silently breaking BaseSandbox-generated edit/write scripts.
            shell_cmd = ["timeout", str(int(timeout)), "bash", "-c", command]
        else:
            shell_cmd = ["bash", "-c", command]

        result = self._container.exec_run(
            shell_cmd,
            stdout=True,
            stderr=True,
            workdir=self._workspace,
        )
        output = result.output.decode("utf-8", errors="replace") if result.output else ""
        return ExecuteResponse(
            output=output,
            exit_code=result.exit_code,
            truncated=False,
        )

    def upload_files(
        self,
        files: list[tuple[str, bytes]],
    ) -> list[FileUploadResponse]:
        """Upload files into the container using the Docker tar-archive API.

        Each file is packed into a single-entry in-memory tar archive and
        transferred via :meth:`docker.models.containers.Container.put_archive`.
        Parent directories are created with ``mkdir -p`` before the upload.

        Args:
            files: List of ``(absolute_path, content)`` tuples.

        Returns:
            One :class:`~deepagents.backends.protocol.FileUploadResponse` per
            input file, in the same order.  ``error`` is ``None`` on success.
        """
        results: list[FileUploadResponse] = []
        for path, content in files:
            try:
                dir_path = os.path.dirname(path) or "/"
                # ensure parent directory exists inside the container
                mkdir_result = self._container.exec_run(
                    ["bash", "-c", f"mkdir -p {shlex.quote(dir_path)}"],
                    workdir=self._workspace,
                )
                if mkdir_result.exit_code != 0:
                    err = (mkdir_result.output or b"").decode("utf-8", errors="replace").strip()
                    results.append(
                        FileUploadResponse(
                            path=path,
                            error=f"mkdir -p {dir_path!r} failed (exit {mkdir_result.exit_code}): {err}",
                        )
                    )
                    continue
                # build a single-file tar archive in memory
                tar_stream = io.BytesIO()
                with tarfile.open(fileobj=tar_stream, mode="w") as tar:
                    info = tarfile.TarInfo(name=os.path.basename(path))
                    info.size = len(content)
                    tar.addfile(info, io.BytesIO(content))
                tar_stream.seek(0)
                self._container.put_archive(dir_path, tar_stream)
                results.append(FileUploadResponse(path=path))
            except Exception as exc:  # noqa: BLE001
                results.append(FileUploadResponse(path=path, error=str(exc)))
        return results

    def download_files(
        self,
        paths: list[str],
    ) -> list[FileDownloadResponse]:
        """Download files from the container using the Docker tar-archive API.

        Calls :meth:`docker.models.containers.Container.get_archive` and
        extracts the file content from the returned tar stream.

        Args:
            paths: List of absolute file paths inside the container.

        Returns:
            One :class:`~deepagents.backends.protocol.FileDownloadResponse`
            per input path, in the same order.  ``error`` is ``None`` on
            success.
        """
        results: list[FileDownloadResponse] = []
        for path in paths:
            try:
                bits, _ = self._container.get_archive(path)
                tar_data = b"".join(bits)
                with tarfile.open(fileobj=io.BytesIO(tar_data)) as tar:
                    member = tar.getmember(os.path.basename(path))
                    f = tar.extractfile(member)
                    content = f.read() if f else b""
                results.append(FileDownloadResponse(path=path, content=content))
            except Exception as exc:  # noqa: BLE001
                results.append(FileDownloadResponse(path=path, error=str(exc)))
        return results


def create_docker_sandbox(sandbox_id: str | None = None) -> DockerSandbox:
    """Create or reconnect to a Docker container sandbox.

    Requires Docker Desktop (or Docker Engine) to be installed and running,
    and the ``docker`` Python package to be available.  Install it with::

        pip install docker

    Args:
        sandbox_id: Optional existing container ID or name to reconnect to.
            If the container is stopped it will be restarted.
            If ``None``, a new container is created from the configured image.

    Returns:
        :class:`DockerSandbox` instance implementing
        ``SandboxBackendProtocol``.

    Raises:
        ImportError: When the ``docker`` package is not installed.
        docker.errors.DockerException: When the Docker daemon is unreachable.
    """
    try:
        import docker as _docker
    except ImportError as exc:
        raise ImportError(
            "The 'docker' package is required for SANDBOX_TYPE=docker. "
            "Install it with: pip install docker"
        ) from exc

    image = os.getenv(DOCKER_IMAGE_ENV, DOCKER_DEFAULT_IMAGE)
    workspace = os.getenv(DOCKER_WORKSPACE_ENV, DOCKER_DEFAULT_WORKSPACE)

    client = _docker.from_env()

    if sandbox_id:
        container = client.containers.get(sandbox_id)
        if container.status != "running":
            container.start()
    else:
        container = client.containers.run(
            image,
            command="tail -f /dev/null",
            detach=True,
            remove=False,
            working_dir=workspace,
        )
        # ensure workspace directory exists inside the freshly created container
        container.exec_run(
            ["bash", "-c", f"mkdir -p {shlex.quote(workspace)}"],
            workdir="/",
        )

    return DockerSandbox(container, workspace=workspace)
